name: Build Windows App

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: 21
        
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Garble
      run: go install mvdan.cc/garble@latest

    - name: Build Windows App
      run: |
        cd frontend
        npm i
        cd ..
        wails build -obfuscated -upx
        mv build/bin/desmume-launcher.exe build/bin/DeSmuME.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DeSmuME
        path: build/bin/DeSmuME.exe
